server:
  port: 6060
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sai
    password: sai 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true  
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true